import 'dart:io';
import 'package:share_plus/share_plus.dart';

class ShareService {
  /// Share PDF file via WhatsApp or any other app
  Future<void> sharePdf(File pdfFile, {String? subject}) async {
    await Share.shareXFiles(
      [XFile(pdfFile.path, mimeType: 'application/pdf')],
      subject: subject ?? 'Cricket Match Report',
      text: '🏏 Check out this cricket match report!',
    );
  }

  /// Share text score update
  Future<void> shareScore(String scoreText) async {
    await Share.share(
      scoreText,
      subject: 'Cricket Score Update',
    );
  }

  /// Share full scorecard as text
  Future<void> shareScorecard({
    required String teamAName,
    required String teamBName,
    required String teamAScore,
    required String teamBScore,
    required String result,
    required String date,
  }) async {
    final text = '''
🏏 CRICKET MATCH SCORECARD

$teamAName vs $teamBName
📅 $date

🏏 $teamAName: $teamAScore
🏏 $teamBName: $teamBScore

🏆 Result: $result

Generated by Cricket Scorer App
''';
    await Share.share(text, subject: 'Match Scorecard');
  }
}
