// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRyAHPbYRYL4PAr4e1ZW_RRbKuyWv60gI',
    appId: '1:465584382891:web:773e774cda319413e2e8ee',
    messagingSenderId: '465584382891',
    projectId: 'scorebook-17985',
    authDomain: 'scorebook-17985.firebaseapp.com',
    databaseURL: 'https://scorebook-17985-default-rtdb.firebaseio.com',
    storageBucket: 'scorebook-17985.firebasestorage.app',
    measurementId: 'G-M3S486TL7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvVgm464uOGWYlCTy1b2ZX6Y_u96dUsU8',
    appId: '1:465584382891:android:060d89c654b1d954e2e8ee',
    messagingSenderId: '465584382891',
    projectId: 'scorebook-17985',
    authDomain: 'scorebook-17985.firebaseapp.com',
    databaseURL: 'https://scorebook-17985-default-rtdb.firebaseio.com',
    storageBucket: 'scorebook-17985.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQMhDJCWi_zcvsCU1jI1nzkYADywMJ9fQ',
    appId: '1:465584382891:ios:05ff19dfea58f8aee2e8ee',
    messagingSenderId: '465584382891',
    projectId: 'scorebook-17985',
    authDomain: 'scorebook-17985.firebaseapp.com',
    databaseURL: 'https://scorebook-17985-default-rtdb.firebaseio.com',
    storageBucket: 'scorebook-17985.firebasestorage.app',
    iosBundleId: 'com.example.scoringCount',
  );

}